"""add created_at to leave_info

Revision ID: 69822e79e5d8
Revises: 76061397e8af
Create Date: 2026-05-08 22:57:56.161021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69822e79e5d8'
down_revision = '76061397e8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_info', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
