"""add password_hash to user_info

Revision ID: 76061397e8af
Revises: fa773ecf9cae
Create Date: 2026-05-08 21:55:05.192080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76061397e8af'
down_revision = 'fa773ecf9cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
